apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    db: postgres
spec:
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        db: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:12
          # ports:
          #   - containerPort: 5432
          env:
              - name: POSTGRES_USER
                value: "postgres"
              - name: POSTGRES_PASSWORD
                value: "postgres"
              - name: POSTGRES_HOST_AUTH_METHOD
                value: trust
  replicas: 1
